import type { Metadata } from "next";
import { DM_Sans, DM_Mono } from "next/font/google";
import "./globals.css";

const DMSans = DM_Sans({
  variable: "--font-DM-sans",
  subsets: ["latin"],
});
const DMMono = DM_Mono({
  variable: "--font-DM-mono",
  subsets: ["latin"],
  weight: ["300", "400", "500"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${DMSans.variable} ${DMMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
